working_directory = "None"

[bell]
animation = "Ease"
color = "#f48ead"
duration = 0

[[colors.indexed_colors]]
color = "#f48ead"
index = 16

[colors.normal]
black = "#4e4e4e"
blue = "#5f87ae"
cyan = "#5f8787"
green = "#5f885f"
magenta = "#875f87"
red = "#af5f5f"
white = "#e4e4e4"
yellow = "#af8760"

[colors.cursor]
cursor = "#4e4e4e"

[colors.bright]
black = "#3a3a3a"
blue = "#0087af"
cyan = "#008787"
green = "#005f00"
magenta = "#87025f"
red = "#870100"
white = "#eeeeee"
yellow = "#d8865f"

[colors.primary]
background = "#E9E9E9"
foreground = "#4e4e4e"

[colors.selection]
background = "#afd7d7"
text = "#005f5f"

# [colors.bright]
# black = "#686868"
# blue = "#73d0ff"
# cyan = "#95e6cb"
# green = "#bae67e"
# magenta = "#d4bfff"
# red = "#f28779"
# white = "#ffffff"
# yellow = "#ffd580"
# 
# [colors.cursor]
# cursor = "#ffffff"
# 
# [colors.normal]
# black = "#191e2a"
# blue = "#6dcbfa"
# cyan = "#90e1c6"
# green = "#a6cc70"
# magenta = "#cfbafa"
# red = "#ed8274"
# white = "#c7c7c7"
# yellow = "#fad07b"
# 
# [colors.primary]
# background = "#1f2430"
# foreground = "#cbccc6"
# 
# [colors.selection]
# background = "#33415E"
# text = "#CBCCC6"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-alacritty"

[font]
size = 7.4
# size = 13

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Maximized"
title = "Terminal"
# opacity = 0.7

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 0
