#!/usr/bin/sh

curStatus=$(playerctl status --player $(~/bin/get-active-player))

if [[ "$curStatus" = "Playing" || "$curStatus" = "Paused" ]]; then
    if [[ "$curStatus" = "Paused" ]]; then
        echo 
    elif [[ "$curStatus" = "Playing" ]]; then
        echo 
    fi
fi
