#!/usr/bin/sh

curStatus=$(playerctl status --player $(~/bin/get-active-player))
npCommand="playerctl metadata --player $(~/bin/get-active-player) -f {{title}}"

if [[ "$curStatus" = "Playing" || "$curStatus" = "Paused" ]]; then
    if [ "$($npCommand)" ]; then
        nowPlaying=$(${npCommand} | cut -c 1-50 | iconv -f utf-8 -t utf-8 -c) # We use iconv here to strip non UTF-8 characters from the string, so that it doesn't crash polybar
    else
        nowPlaying="Untitled"
    fi
else
    nowPlaying="Nothing playing"
fi
echo "$nowPlaying"
