#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width   2
bspc config window_gap     2
bspc config bottom_padding 24

bspc config focused_border_color "#A29BFE"
bspc config normal_border_color  "#1F2430"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Start picom compositor
picom -b

# Set desktop wallpaper
~/.fehbg

# Start notification daemon
dunst &

# Start flameshot service
flameshot &

# Launch polybar
~/.config/polybar/custom/launch.sh
