#!/bin/sh
CURRENT_SINK_RAW=$( pactl list sinks short | grep RUNNING | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' )
[ $CURRENT_SINK_RAW ] && SINK=$CURRENT_SINK_RAW || SINK='@DEFAULT_SINK@'

# argv will always be one of '+' or '-'
pactl set-sink-volume $SINK "$15%"

curidx=$(pacmd list-sinks | awk '/^\s+\* index/ {print $3}')
current=$(pacmd dump-volumes | awk "/^Sink ${curidx}/{print \$8}" | sed 's/\%//')
muted=$(pacmd list-sinks | tr -d '\n' | sed 's/.*?* index//' | sed 's/.*muted://' | awk '{print $1}')

[ $current -gt 100  ] && pactl set-sink-volume @DEFAULT_SINK@ 100%

case $muted in
    "yes")
        dunstify -h int:value:$current -a "bright_or_vol_change" -u low " Volume: " -r 2
        ;;
    "no")
        dunstify -h int:value:$current -a "bright_or_vol_change" -u low " Volume: " -r 2
esac
