#!/bin/sh
CURRENT_SINK_RAW=$( pactl list sinks short | grep RUNNING | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' )
[ $CURRENT_SINK_RAW ] && SINK=$CURRENT_SINK_RAW || SINK='@DEFAULT_SINK@'

# argv will always be one of '+' or '-'
pactl set-sink-volume $SINK "$15%"

current=$(pacmd dump-volumes | awk 'NR==1{print $8}' | sed 's/\%//')
muted=$(pactl list sinks | awk '/Mute/ {print $2}')

[ $current -gt 100  ] && pactl set-sink-volume @DEFAULT_SINK@ 100%

case $muted in
    "yes")
        dunstify -h int:value:$current -a "Brightness or Volume Level Adjusted" -u low " Volume: " -r 2
        ;;
    "no")
        dunstify -h int:value:$current -a "Brightness or Volume Level Adjusted" -u low " Volume: " -r 2
esac
